'use client'

import { useState } from 'react'
import { toast } from 'sonner'

interface ReportStats {
  totalStaff: number
  totalAssessments: number
  passedAssessments: number
  failedAssessments: number
  activeCerts: number
  expiredCerts: number
  expiringCerts: number
  passRate: number
  hospitalName?: string
}

export default function ReportExporter({ stats }: { stats: ReportStats }) {
  const [exportingExcel, setExportingExcel] = useState(false)
  const [exportingPdf, setExportingPdf] = useState(false)

  async function exportExcel() {
    setExportingExcel(true)
    try {
      const XLSX = await import('xlsx')

      const summarySheet = XLSX.utils.aoa_to_sheet([
        ['CAMS — Compliance Report Summary'],
        ['Hospital', stats.hospitalName ?? 'All Hospitals'],
        ['Generated', new Date().toLocaleDateString('en-SA')],
        [],
        ['Metric', 'Value', '% of Total'],
        ['Active Staff', stats.totalStaff, ''],
        ['Total Assessments', stats.totalAssessments, '100%'],
        ['Passed Assessments', stats.passedAssessments, `${stats.passRate}%`],
        ['Failed Assessments', stats.failedAssessments, `${stats.totalAssessments > 0 ? Math.round((stats.failedAssessments / stats.totalAssessments) * 100) : 0}%`],
        ['Active Certificates', stats.activeCerts, ''],
        ['Expiring Certificates', stats.expiringCerts, ''],
        ['Expired Certificates', stats.expiredCerts, ''],
      ])

      const certsSheet = XLSX.utils.aoa_to_sheet([
        ['Certificate Status Report'],
        [],
        ['Status', 'Count'],
        ['Active', stats.activeCerts],
        ['Expiring Soon', stats.expiringCerts],
        ['Expired', stats.expiredCerts],
        ['Total', stats.activeCerts + stats.expiringCerts + stats.expiredCerts],
      ])

      const wb = XLSX.utils.book_new()
      XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary')
      XLSX.utils.book_append_sheet(wb, certsSheet, 'Certificates')

      const filename = `CAMS-Report-${new Date().toISOString().split('T')[0]}.xlsx`
      XLSX.writeFile(wb, filename)
      toast.success('Excel report downloaded')
    } catch (err) {
      console.error(err)
      toast.error('Failed to export Excel')
    } finally {
      setExportingExcel(false)
    }
  }

  async function exportPdf() {
    setExportingPdf(true)
    try {
      const { default: jsPDF } = await import('jspdf')
      const { default: autoTable } = await import('jspdf-autotable')

      const doc = new jsPDF()

      // Header
      doc.setFillColor(11, 31, 58)
      doc.rect(0, 0, 210, 40, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(18)
      doc.setFont('helvetica', 'bold')
      doc.text('CAMS — Compliance Report', 14, 20)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.text(`${stats.hospitalName ?? 'All Hospitals'} · ${new Date().toLocaleDateString('en-SA')}`, 14, 30)

      doc.setTextColor(0, 0, 0)

      // Summary stats
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text('Executive Summary', 14, 56)

      autoTable(doc, {
        startY: 62,
        head: [['Metric', 'Value', '% of Total']],
        body: [
          ['Active Staff', String(stats.totalStaff), ''],
          ['Total Assessments', String(stats.totalAssessments), '100%'],
          ['Passed Assessments', String(stats.passedAssessments), `${stats.passRate}%`],
          ['Failed Assessments', String(stats.failedAssessments), `${stats.totalAssessments > 0 ? Math.round((stats.failedAssessments / stats.totalAssessments) * 100) : 0}%`],
        ],
        headStyles: { fillColor: [21, 101, 192], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        styles: { fontSize: 10 },
      })

      const afterTable = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14

      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text('Certificate Status', 14, afterTable)

      autoTable(doc, {
        startY: afterTable + 6,
        head: [['Status', 'Count']],
        body: [
          ['Active', String(stats.activeCerts)],
          ['Expiring Soon (30 days)', String(stats.expiringCerts)],
          ['Expired', String(stats.expiredCerts)],
        ],
        headStyles: { fillColor: [0, 150, 136], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 252, 250] },
        styles: { fontSize: 10 },
      })

      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by CAMS — Competency Assessment Management System', 14, 285)

      doc.save(`CAMS-Report-${new Date().toISOString().split('T')[0]}.pdf`)
      toast.success('PDF report downloaded')
    } catch (err) {
      console.error(err)
      toast.error('Failed to export PDF')
    } finally {
      setExportingPdf(false)
    }
  }

  return (
    <div style={{ display: 'flex', gap: 8 }}>
      <button
        className="btn btn-secondary btn-sm"
        onClick={exportExcel}
        disabled={exportingExcel}
      >
        {exportingExcel ? '⏳ Exporting…' : '📥 Export Excel'}
      </button>
      <button
        className="btn btn-secondary btn-sm"
        onClick={exportPdf}
        disabled={exportingPdf}
      >
        {exportingPdf ? '⏳ Exporting…' : '📄 Export PDF'}
      </button>
    </div>
  )
}
