'use client'

import { useState } from 'react'
import { toast } from 'sonner'
import { MonthlyLine, ComplianceBar } from '@/components/charts/Charts'
import { getRoleLabel } from '@/lib/utils'

interface HospitalRow {
  id: string
  name: string
  is_active: boolean
  plan: string
  expires: string | null
  staff: number
  assessments: number
  compliance: number
  activeCerts: number
  revenue: number
  city: string
}

interface PlatformData {
  totalRevenue: number
  pendingRevenue: number
  paidInvoices: number
  unpaidInvoices: number
  revenueTrend: { month: string; revenue: number; count: number }[]
  totalHospitals: number
  activeHospitals: number
  suspendedHospitals: number
  expiredPlans: number
  expiringSoon: number
  pendingSignups: number
  approvedSignups: number
  totalUsers: number
  activeUsers: number
  roleBreakdown: Record<string, number>
  totalAssessments: number
  passed: number
  failed: number
  platformPassRate: number
  activeCerts: number
  expiredCerts: number
  hospitalBreakdown: HospitalRow[]
}

export default function SuperAdminReportsClient({ data }: { data: PlatformData }) {
  const [search, setSearch] = useState('')
  const [sortBy, setSortBy] = useState<'name' | 'staff' | 'compliance' | 'revenue'>('revenue')
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc')
  const [activeTab, setActiveTab] = useState<'overview' | 'financial' | 'hospitals' | 'users'>('overview')

  const revenueTrendFormatted = data.revenueTrend.map((r) => ({ month: r.month, count: r.revenue }))

  async function exportExcel() {
    try {
      const XLSX = await import('xlsx')
      const rows: unknown[][] = [
        ['Hospital', 'Status', 'Plan', 'Expires', 'Staff', 'Assessments', 'Compliance %', 'Active Certs', 'Revenue (SAR)', 'City'],
        ...filtered.map((h) => [
          h.name, h.is_active ? 'Active' : 'Suspended', h.plan,
          h.expires ? new Date(h.expires).toLocaleDateString('en-CA') : '—',
          h.staff, h.assessments, `${h.compliance}%`, h.activeCerts,
          h.revenue.toLocaleString(), h.city,
        ]),
      ]
      const ws = XLSX.utils.aoa_to_sheet(rows)
      const wb = XLSX.utils.book_new()
      XLSX.utils.book_append_sheet(wb, ws, 'Platform Report')
      XLSX.writeFile(wb, `CAMS-Platform-Report-${new Date().toISOString().split('T')[0]}.xlsx`)
      toast.success('Excel exported')
    } catch { toast.error('Export failed') }
  }

  async function exportPdf() {
    try {
      const { default: jsPDF } = await import('jspdf')
      const { default: autoTable } = await import('jspdf-autotable')
      const doc = new jsPDF({ orientation: 'landscape' })

      doc.setFillColor(11, 31, 58)
      doc.rect(0, 0, 297, 40, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      doc.text('CAMS — Platform Report (Super Admin)', 14, 18)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.text(`Generated ${new Date().toLocaleDateString('en-CA')} · ${data.totalHospitals} hospitals · SAR ${Math.round(data.totalRevenue).toLocaleString()} total revenue`, 14, 30)
      doc.setTextColor(0, 0, 0)

      autoTable(doc, {
        startY: 50,
        head: [['Hospital', 'Status', 'Plan', 'Staff', 'Assessments', 'Compliance %', 'Revenue (SAR)']],
        body: filtered.map((h) => [
          h.name, h.is_active ? 'Active' : 'Suspended', h.plan,
          h.staff, h.assessments, `${h.compliance}%`, `SAR ${h.revenue.toLocaleString()}`,
        ]),
        headStyles: { fillColor: [21, 101, 192], textColor: 255, fontSize: 9 },
        alternateRowStyles: { fillColor: [245, 248, 255] },
        styles: { fontSize: 8, cellPadding: 3 },
      })

      doc.setFontSize(7)
      doc.setTextColor(150)
      doc.text('Generated by CAMS — Competency Assessment Management System (Super Admin Only)', 14, doc.internal.pageSize.height - 8)
      doc.save(`CAMS-Platform-Report-${new Date().toISOString().split('T')[0]}.pdf`)
      toast.success('PDF exported')
    } catch (e) { console.error(e); toast.error('PDF export failed') }
  }

  function toggleSort(col: typeof sortBy) {
    if (sortBy === col) setSortDir((d) => d === 'asc' ? 'desc' : 'asc')
    else { setSortBy(col); setSortDir('desc') }
  }

  const sortIcon = (col: typeof sortBy) =>
    sortBy === col ? (sortDir === 'desc' ? ' ▼' : ' ▲') : ' ↕'

  const filtered = data.hospitalBreakdown
    .filter((h) => !search || h.name.toLowerCase().includes(search.toLowerCase()) || h.city.toLowerCase().includes(search.toLowerCase()))
    .sort((a, b) => {
      const mul = sortDir === 'asc' ? 1 : -1
      if (sortBy === 'name') return mul * a.name.localeCompare(b.name)
      if (sortBy === 'staff') return mul * (a.staff - b.staff)
      if (sortBy === 'compliance') return mul * (a.compliance - b.compliance)
      return mul * (a.revenue - b.revenue)
    })

  const now = new Date()

  const tabs = [
    { id: 'overview', label: '📊 Overview' },
    { id: 'financial', label: '💰 Financial' },
    { id: 'hospitals', label: '🏥 Hospitals' },
    { id: 'users', label: '👥 Users & Roles' },
  ] as const

  return (
    <>
      {/* Export buttons */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginBottom: 16 }}>
        <button className="btn btn-secondary btn-sm" onClick={exportExcel}>📥 Export Excel</button>
        <button className="btn btn-secondary btn-sm" onClick={exportPdf}>📄 Export PDF</button>
      </div>

      {/* Top KPIs */}
      <div className="kpi-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: 20 }}>
        <div className="kpi-card">
          <div className="kpi-icon" style={{ background: '#E8F5E9' }}>💰</div>
          <div className="kpi-label">Total Revenue</div>
          <div className="kpi-value" style={{ fontSize: 18 }}>SAR {Math.round(data.totalRevenue).toLocaleString()}</div>
          <div className="kpi-change">{data.paidInvoices} paid invoices</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-icon" style={{ background: '#FFF8E1' }}>⏳</div>
          <div className="kpi-label">Pending Revenue</div>
          <div className="kpi-value" style={{ fontSize: 18, color: data.pendingRevenue > 0 ? '#F57F17' : 'inherit' }}>
            SAR {Math.round(data.pendingRevenue).toLocaleString()}
          </div>
          <div className="kpi-change">{data.unpaidInvoices} unpaid invoices</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-icon" style={{ background: '#E3F2FD' }}>🏥</div>
          <div className="kpi-label">Active Hospitals</div>
          <div className="kpi-value">{data.activeHospitals}</div>
          <div className="kpi-change">{data.totalHospitals} total</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-icon" style={{ background: '#F3E5F5' }}>👥</div>
          <div className="kpi-label">Active Users</div>
          <div className="kpi-value">{data.activeUsers}</div>
          <div className="kpi-change">{data.totalUsers} total</div>
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 20, borderBottom: '2px solid var(--border)', paddingBottom: 0 }}>
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            style={{
              padding: '8px 18px', fontSize: 13, fontWeight: 600, border: 'none', cursor: 'pointer',
              background: activeTab === t.id ? 'white' : 'transparent',
              borderBottom: activeTab === t.id ? '2px solid var(--blue)' : '2px solid transparent',
              color: activeTab === t.id ? 'var(--blue)' : 'var(--gray-500)',
              borderRadius: '6px 6px 0 0', marginBottom: -2,
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* OVERVIEW TAB */}
      {activeTab === 'overview' && (
        <>
          <div className="grid-2" style={{ gap: 20, marginBottom: 20 }}>
            <div className="card">
              <div className="card-header"><div className="card-title">Platform Assessments Summary</div></div>
              <div className="card-body">
                <div style={{ display: 'flex', gap: 32, flexWrap: 'wrap' }}>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Platform Pass Rate</div>
                    <div style={{ fontSize: 32, fontWeight: 700, color: 'var(--green)' }}>{data.platformPassRate}%</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Total Assessments</div>
                    <div style={{ fontSize: 32, fontWeight: 700 }}>{data.totalAssessments}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Passed</div>
                    <div style={{ fontSize: 32, fontWeight: 700, color: 'var(--green)' }}>{data.passed}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Failed</div>
                    <div style={{ fontSize: 32, fontWeight: 700, color: 'var(--red)' }}>{data.failed}</div>
                  </div>
                </div>
                <div style={{ marginTop: 16 }}>
                  <div style={{ background: '#eee', borderRadius: 8, height: 12, overflow: 'hidden' }}>
                    <div style={{ width: `${data.platformPassRate}%`, height: '100%', background: 'var(--green)', borderRadius: 8 }} />
                  </div>
                  <div style={{ fontSize: 11, color: 'var(--gray-400)', marginTop: 4 }}>Overall compliance across all hospitals</div>
                </div>
              </div>
            </div>

            <div className="card">
              <div className="card-header"><div className="card-title">Hospital Status</div></div>
              <div className="card-body">
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                  {[
                    { label: 'Active', value: data.activeHospitals, color: 'var(--green)', bg: '#E8F5E9' },
                    { label: 'Suspended', value: data.suspendedHospitals, color: 'var(--red)', bg: '#FFEBEE' },
                    { label: 'Expiring Soon (30d)', value: data.expiringSoon, color: '#F57F17', bg: '#FFF8E1' },
                    { label: 'Expired Plans', value: data.expiredPlans, color: 'var(--red)', bg: '#FFEBEE' },
                  ].map((s) => (
                    <div key={s.label} style={{ background: s.bg, borderRadius: 10, padding: '12px 16px' }}>
                      <div style={{ fontSize: 11, color: s.color, fontWeight: 600 }}>{s.label}</div>
                      <div style={{ fontSize: 26, fontWeight: 700, color: s.color }}>{s.value}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="grid-2" style={{ gap: 20, marginBottom: 20 }}>
            <div className="card">
              <div className="card-header"><div className="card-title">Certificates Summary</div></div>
              <div className="card-body">
                <div style={{ display: 'flex', gap: 24 }}>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Active Certs</div>
                    <div style={{ fontSize: 26, fontWeight: 700, color: 'var(--green)' }}>{data.activeCerts}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Expired Certs</div>
                    <div style={{ fontSize: 26, fontWeight: 700, color: 'var(--red)' }}>{data.expiredCerts}</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="card">
              <div className="card-header"><div className="card-title">Signup Pipeline</div></div>
              <div className="card-body">
                <div style={{ display: 'flex', gap: 24 }}>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Pending Signups</div>
                    <div style={{ fontSize: 26, fontWeight: 700, color: data.pendingSignups > 0 ? '#F57F17' : 'inherit' }}>{data.pendingSignups}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-400)' }}>Approved</div>
                    <div style={{ fontSize: 26, fontWeight: 700, color: 'var(--green)' }}>{data.approvedSignups}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {/* FINANCIAL TAB */}
      {activeTab === 'financial' && (
        <>
          <div className="kpi-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: 20 }}>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E8F5E9' }}>💰</div>
              <div className="kpi-label">Total Revenue</div>
              <div className="kpi-value" style={{ fontSize: 16 }}>SAR {Math.round(data.totalRevenue).toLocaleString()}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#FFF8E1' }}>⏳</div>
              <div className="kpi-label">Pending</div>
              <div className="kpi-value" style={{ fontSize: 16, color: data.pendingRevenue > 0 ? '#F57F17' : 'inherit' }}>
                SAR {Math.round(data.pendingRevenue).toLocaleString()}
              </div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E3F2FD' }}>🧾</div>
              <div className="kpi-label">Paid Invoices</div>
              <div className="kpi-value">{data.paidInvoices}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#FFEBEE' }}>❌</div>
              <div className="kpi-label">Unpaid Invoices</div>
              <div className="kpi-value" style={{ color: data.unpaidInvoices > 0 ? 'var(--red)' : 'inherit' }}>{data.unpaidInvoices}</div>
            </div>
          </div>

          <div className="card" style={{ marginBottom: 20 }}>
            <div className="card-header"><div className="card-title">Monthly Revenue Trend (SAR)</div></div>
            <div className="card-body">
              <MonthlyLine data={revenueTrendFormatted} color="#2E7D32" label="Revenue (SAR)" />
            </div>
          </div>

          <div className="card">
            <div className="card-header"><div className="card-title">Revenue by Hospital</div></div>
            <div className="card-body p-0">
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Hospital</th>
                      <th>Plan</th>
                      <th>Status</th>
                      <th>Expires</th>
                      <th style={{ textAlign: 'right' }}>Revenue (SAR)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.hospitalBreakdown
                      .sort((a, b) => b.revenue - a.revenue)
                      .map((h) => {
                        const expired = h.expires && new Date(h.expires) < now
                        return (
                          <tr key={h.id}>
                            <td style={{ fontWeight: 600 }}>{h.name}</td>
                            <td><span className="badge badge-blue">{h.plan}</span></td>
                            <td>
                              {h.is_active
                                ? <span className="badge badge-green">Active</span>
                                : <span className="badge badge-red">Suspended</span>}
                            </td>
                            <td style={{ color: expired ? 'var(--red)' : 'inherit', fontSize: 12 }}>
                              {h.expires ? new Date(h.expires).toLocaleDateString('en-CA') : '—'}
                              {expired && ' ⚠️'}
                            </td>
                            <td style={{ textAlign: 'right', fontWeight: 700, color: 'var(--green)' }}>
                              {h.revenue > 0 ? `SAR ${h.revenue.toLocaleString()}` : '—'}
                            </td>
                          </tr>
                        )
                      })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </>
      )}

      {/* HOSPITALS TAB */}
      {activeTab === 'hospitals' && (
        <>
          <div className="card" style={{ marginBottom: 16 }}>
            <div className="card-body" style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}>
              <div style={{ flex: '1 1 240px' }}>
                <label className="form-label">Search</label>
                <input
                  className="form-input"
                  placeholder="Hospital name or city…"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>
              <div style={{ marginLeft: 'auto', fontSize: 12, color: 'var(--gray-500)', alignSelf: 'center' }}>
                {filtered.length} of {data.hospitalBreakdown.length} hospitals
              </div>
            </div>
          </div>

          <div className="card" style={{ marginBottom: 20 }}>
            <div className="card-header"><div className="card-title">Hospital Compliance Comparison</div></div>
            <div className="card-body">
              <ComplianceBar
                data={data.hospitalBreakdown.slice(0, 12).map((h) => ({ name: h.name.length > 14 ? h.name.slice(0, 14) + '…' : h.name, compliance: h.compliance }))}
                label="Compliance %"
              />
            </div>
          </div>

          <div className="card">
            <div className="card-body p-0">
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th onClick={() => toggleSort('name')} style={{ cursor: 'pointer' }}>Hospital{sortIcon('name')}</th>
                      <th>City</th>
                      <th>Plan</th>
                      <th>Status</th>
                      <th>Expires</th>
                      <th onClick={() => toggleSort('staff')} style={{ cursor: 'pointer' }}>Staff{sortIcon('staff')}</th>
                      <th>Assessments</th>
                      <th onClick={() => toggleSort('compliance')} style={{ cursor: 'pointer' }}>Compliance{sortIcon('compliance')}</th>
                      <th>Active Certs</th>
                      <th onClick={() => toggleSort('revenue')} style={{ cursor: 'pointer' }}>Revenue{sortIcon('revenue')}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((h) => {
                      const expired = h.expires && new Date(h.expires) < now
                      const expiringSoon = h.expires && !expired && (new Date(h.expires).getTime() - now.getTime()) / 86400000 <= 30
                      return (
                        <tr key={h.id}>
                          <td style={{ fontWeight: 600 }}>{h.name}</td>
                          <td className="text-sm text-muted">{h.city}</td>
                          <td><span className="badge badge-blue" style={{ fontSize: 10 }}>{h.plan}</span></td>
                          <td>
                            {h.is_active
                              ? <span className="badge badge-green">Active</span>
                              : <span className="badge badge-red">Suspended</span>}
                          </td>
                          <td style={{ fontSize: 11, color: expired ? 'var(--red)' : expiringSoon ? '#F57F17' : 'var(--gray-500)' }}>
                            {h.expires ? new Date(h.expires).toLocaleDateString('en-CA') : '—'}
                            {expired && ' ⚠️'}{expiringSoon && ' ⏰'}
                          </td>
                          <td style={{ fontWeight: 600 }}>{h.staff}</td>
                          <td className="text-sm text-muted">{h.assessments}</td>
                          <td>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                              <div style={{ width: 50, background: '#eee', borderRadius: 4, height: 6, overflow: 'hidden' }}>
                                <div style={{ width: `${h.compliance}%`, height: '100%', background: h.compliance >= 70 ? 'var(--green)' : 'var(--red)' }} />
                              </div>
                              <span style={{ fontSize: 12, fontWeight: 600 }}>{h.compliance}%</span>
                            </div>
                          </td>
                          <td style={{ color: 'var(--green)', fontWeight: 600 }}>{h.activeCerts}</td>
                          <td style={{ fontWeight: 700, fontSize: 12 }}>
                            {h.revenue > 0 ? `SAR ${h.revenue.toLocaleString()}` : '—'}
                          </td>
                        </tr>
                      )
                    })}
                    {filtered.length === 0 && (
                      <tr>
                        <td colSpan={10} style={{ textAlign: 'center', color: 'var(--gray-400)', padding: 32 }}>
                          No hospitals found
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </>
      )}

      {/* USERS TAB */}
      {activeTab === 'users' && (
        <>
          <div className="kpi-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: 20 }}>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E3F2FD' }}>👥</div>
              <div className="kpi-label">Total Users</div>
              <div className="kpi-value">{data.totalUsers}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E8F5E9' }}>✅</div>
              <div className="kpi-label">Active Users</div>
              <div className="kpi-value">{data.activeUsers}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E0F2F1' }}>✅</div>
              <div className="kpi-label">Total Assessments</div>
              <div className="kpi-value">{data.totalAssessments}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-icon" style={{ background: '#E8F5E9' }}>📊</div>
              <div className="kpi-label">Platform Pass Rate</div>
              <div className="kpi-value" style={{ color: 'var(--green)' }}>{data.platformPassRate}%</div>
            </div>
          </div>

          <div className="card">
            <div className="card-header"><div className="card-title">Users by Role</div></div>
            <div className="card-body p-0">
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Role</th>
                      <th>Count</th>
                      <th>% of Total</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(data.roleBreakdown)
                      .sort((a, b) => b[1] - a[1])
                      .map(([role, count]) => (
                        <tr key={role}>
                          <td style={{ fontWeight: 600 }}>{getRoleLabel(role)}</td>
                          <td style={{ fontWeight: 700 }}>{count}</td>
                          <td style={{ fontSize: 12, color: 'var(--gray-500)' }}>
                            {data.totalUsers > 0 ? Math.round((count / data.totalUsers) * 100) : 0}%
                          </td>
                          <td style={{ width: 160 }}>
                            <div style={{ background: '#eee', borderRadius: 4, height: 8, overflow: 'hidden' }}>
                              <div style={{
                                width: `${data.totalUsers > 0 ? Math.round((count / data.totalUsers) * 100) : 0}%`,
                                height: '100%', background: 'var(--blue)',
                              }} />
                            </div>
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  )
}
